import type { Metadata } from "next";
import { DM_Sans } from "@next/font/google";
import "./globals.css";
import RouterProvider from "@/components/router-provider";
import { Toaster } from "react-hot-toast";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Captivad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} ${dmSans.className} antialiased`}>
        <Toaster position="top-center" reverseOrder={false} />
        <RouterProvider>{children}</RouterProvider>
      </body>
    </html>
  );
}
